### ISSUE TITLE
support for ES 5

### ISSUE THREAD

**Issue by gupta2007vaibhav** [imperialwicket/elasticsearch-logstash-index-mgmt#23]
Any idea when you will write for ES 5. Bocz in es5 it stored folder with uuid name

**Comment by imperialwicket** [comment]
Hey @gupta2007vaibhav - sorry! I have no plans to update at this point, I'm recommending users transition to elastic's https://github.com/elastic/curator as an alternative. 

I'd consider a Pull Request, but the API has diverged enough that backwards compatibility is no longer a reasonable expectation, and this project wasn't laid out with semver (or any equivalent) in mind.
