### ISSUE TITLE
Add support for multi-node clusters and distributed shards

### ISSUE THREAD

**Issue by imperialwicket** [imperialwicket/elasticsearch-logstash-index-mgmt#7]
Intentionally supporting only nodes that have all data at the moment. 

Discussion:
<dpippen> it looks like 
<dpippen> https://github.com/dpippen/elasticsearch-logstash-index-mgmt/blob/master/elasticsearch-backup-index.sh
<dpippen> assumes a 1 or 2 node ES cluster
...
<dpippen> yeah, it would probably be a matter of grabbing routings and then making a worklist to run on each node
...
<dpippen> if you get the routing and filter for primary shard you might have a list of 7 nodes (some nodes end up with 2 primary shards)
<imperialwicket> to get it running somewhat naturally with the current code, i think i'd want a state entry in redis and strategically offset (via cron) bash scripts.
<imperialwicket> but i really don't feel good about that 
<imperialwicket> wasn't archiving supposed to make it to ES by 1.0?
<dpippen> you could rely on the es notion of the state
<dpippen> dump the mappings, create a snapshot of node and shard assignments 
<dpippen> each node is responsible for making a tar of its shards and copying to S3
<dpippen> so in my example there would be 7 tar files for the index on S3
<imperialwicket> do you want to be able to restore those via script?
<dpippen> the other 13 nodes would just exit, nothing to do
<dpippen> the restore would be similar, just pull down logstash-$DATE-*.tgz

**Comment by hrchu** [comment]
Does these scripts supports multi-node clusters and distributed shard setup? Or should I use curator instead?

**Comment by imperialwicket** [comment]
@hrchu I wouldn't advise using these scripts for multi-node clusters. Generally, I'd recommend using Curator instead at this point. 

Technically these require that each shard be present on localhost (wherever the script is executed), which will work in multi-node clusters as long as you replicate to each node (sometimes practical/appropriate, sometimes not). So if you're in a position where your nodes are just present for backups and growth isn't a concern, these may work. If you're not, or you plan to grow to a point where there is no guarantee that each shard is present on a single running server, Curator is necessary.

In general, Curator's backup technique is more efficient and it is more capable solution. Really the only reasons to use these scripts instead are:
 - You're stuck on < 1.0 Elasticsearch for whatever reason
 - You have a single-node or small cluster for testing or limited scope (in which case these *might* be easier)
